from fastapi import APIRouter
from pydantic import BaseModel

router = APIRouter()

class DocumentRequest(BaseModel):
    prompt: str
    doc_type: str = "Rental Agreement"

class DocumentResponse(BaseModel):
    generated_text: str

@router.post("/generate", response_model=DocumentResponse)
async def generate_document(request: DocumentRequest):
    doc = f"""

                        LEGAL DOCUMENT - {request.doc_type.upper()}
                 Generated by LegalEase AI (Offline Mode - Lab Demo)


Date: 29-09-2026
Place: Chennai, Tamil Nadu

USER PROVIDED DETAILS:
{request.prompt}

PARTIES TO THE AGREEMENT

1. LANDLORD / FIRST PARTY:
   Name: Baranisri
   D/o: ThavaSelvam
   Age: 25 Years
   Address: No. 12, Anna Nagar, Chennai - 600040
   Aadhar: XXXX XXXX 1234
   (Hereinafter referred to as "LANDLORD" which expression shall mean and include his heirs, executors, administrators)

2. TENANT / SECOND PARTY:
   Name: Vijay c
   S/o: chandran
   Age: 28 Years
   Address: No. 45, T Nagar, Chennai
   Aadhar: XXXX XXXX 5678
   (Hereinafter referred to as "TENANT")

WHEREAS the Landlord is the absolute owner of the residential property situated at Chennai and has agreed to let out the same to the Tenant on rental basis.

PAGE 2 - PROPERTY SCHEDULE & FINANCIAL TERMS

3. SCHEDULE OF PROPERTY:
   All that piece and parcel of residential house bearing Door No. 78, Ground Floor, 2BHK, measuring about 950 Sq.ft, situated at Mogappair, Chennai - 600037, with all fittings including 2 Fans, 2 Lights, 1 AC, Modular Kitchen, Water connection.

4. RENT: Rs. 15,000/- (Rupees Fifteen Thousand Only) per English calendar month.

5. SECURITY DEPOSIT: Rs. 50,000/- (Rupees Fifty Thousand Only) interest-free, refundable at end after deductions.

6. DURATION: 11 Months commencing from 01-10-2026 to 31-08-2027.

7. MAINTENANCE: Rs. 1,500/- per month payable by Tenant to Apartment Association.

8. MODE OF PAYMENT: Rent shall be paid on or before 5th of every month via Bank Transfer / GPay to Landlord Account. Late payment attracts Rs. 200 per day penalty.

PAGE 3 - TERMS AND CONDITIONS

9.  The Tenant shall use the premises only for RESIDENTIAL purpose and not for commercial or illegal activities.

10. The Tenant shall not sub-let, assign or part with possession of the scheduled property or any part thereof.

11. The Tenant shall keep the premises in good condition and shall not make any structural alterations without written consent of Landlord.

12. The Tenant shall pay Electricity, Water, Gas, Internet bills separately as per actuals.

13. The Tenant shall allow Landlord to inspect premises with 24 hours prior notice.

14. Minor repairs upto Rs. 2000 shall be borne by Tenant, Major structural repairs by Landlord.

15. Tenant shall not keep any pets without prior permission.

16. Tenant shall not create any nuisance to neighbors. Loud music after 10 PM is strictly prohibited.

PAGE 4 - ADDITIONAL CLAUSES

17. LOCK-IN PERIOD: First 6 months is lock-in. If Tenant vacates before, 2 months rent will be forfeited.

18. NOTICE PERIOD: 2 Months notice must be given by either party for termination after lock-in.

19. RENEWAL: On expiry, agreement may be renewed with 7% increase in rent on mutual consent.

20. SECURITY DEPOSIT REFUND: Landlord shall refund deposit within 15 days of vacating after adjusting unpaid rent, damages, painting charges (Rs. 8000).

21. POLICE VERIFICATION: Tenant agrees for police verification and shall submit ID proofs.

22. FORCE MAJEURE: Neither party liable for failure due to natural calamities, government orders, pandemic.

23. INDEMNITY: Tenant shall indemnify Landlord against any loss due to Tenant's negligence.

24. JURISDICTION: This agreement is governed by laws of India and subject to Chennai Courts.

25. AMENITIES PROVIDED: 1) 2 Wheeler Parking 2) Water 24hrs 3) Lift Facility 4) Security

26. INVENTORY LIST: Fan-3, Light-6, Geyser-1, AC-1 (All in working condition)

PAGE 5 - DECLARATION & SIGNATURES

27. That both parties have read, understood and agreed to all terms above.

28. That this agreement is executed in two originals, one with each party.

29. That the Tenant has confirmed that he has inspected the property and satisfied with condition.

30. That any dispute arising out of this agreement shall be settled by arbitration in Chennai as per Arbitration Act.

IN WITNESS WHEREOF, both parties have set their hands on this day of September 2026 at Chennai.

WITNESSES:

1. Name: Suresh Kumar          Signature: _______________
   Address: Chennai

2. Name: Priya R               Signature: _______________
   Address: Chennai

LANDLORD                                    TENANT

_______________                             _________
 Baranisri TS                                Vijay C

[End of Document - 5 Pages - Generated by LegalEase AI for Lab Demonstration]
[This is a legally valid draft format as per Tamil Nadu Rental Laws 2026]

    """
    return DocumentResponse(generated_text=doc)